name: Compile Binaries
on:
  push:
    branches:
      - master
      - "release/**"
    tags-ignore:
      - '*'
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '**.go'
      - go.mod
      - '.github/workflows/**'
      - '!**_test.go'

env:
  GOPROXY: https://proxy.golang.org,direct
  GO_VERSION: "1.22"

jobs:
  compile-fast:
    runs-on: ubuntu-22.04
    if: github.event.pull_request.draft == true
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run GoReleaser (Fast)
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --config .goreleaser-fast.yml --rm-dist --skip-publish --snapshot --skip-sign

  compile:
    runs-on: ubuntu-22.04
    if: github.event.pull_request.draft != true
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --rm-dist --skip-publish --snapshot --skip-sign
